Melidya2.UI/Models/SepetModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Melidya2.UI.Models
{
    public class SepetModel
    {
        public int ProductID { get; set; }

        public string ProductName { get; set; }

        public int Quantity { get; set; }

        public decimal? Price { get; set; }
    }
}

Melidya2.UI/Controllers/HomeController.cs
using Melidya2.BLL;
using Melidya2.Entity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Melidya2.UI.Controllers
{
    public class HomeController : Controller
    {
        CustomerBLL customerBLL = new CustomerBLL();

        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Login(Customers cust)
        {
            Customers customer = customerBLL.GetCustomer(cust.CustomerID);
            if (customer!= null)
            {
                if (customer.Password == cust.Password)
                {
                    Session["Login"] = customer;
                    return RedirectToAction("Index","Order");
                }
                else
                {
                    return RedirectToAction("LoginHata");
                }
            }
            else
            {
                return RedirectToAction("LoginHata");
            }
        }
        public ActionResult LoginHata()
        {
            return View();
        }

        public ActionResult Logout()
        {
            Session.Remove("Login");
            Session.Clear();
            return RedirectToAction("Login");
        }



    }
}

Melidya2.UI/Controllers/OrderController.cs
using Melidya2.BLL;
using Melidya2.Entity;
using Melidya2.UI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Melidya2.UI.Controllers
{
    public class OrderController : Controller
    {
        OrderBLL orderBLL = new OrderBLL();
        ProductBLL productBLL = new ProductBLL();
        OrderDetailBLL orderdetailBLL = new OrderDetailBLL();

        public ActionResult Index()
        {
            Customers customer = (Customers)Session["Login"];
            List<Orders> orders = orderBLL.GetOrders(customer.CustomerID);

            return View(orders);
        }
        public ActionResult OrderDetail(int id)
        {
            List<Order_Details> order_Details = orderdetailBLL.GetOrder_Details(id);

            return View(order_Details);
        }

        public ActionResult AddOrder()
        {
            Customers customer = Session["Login"] as Customers;
            int orderID = orderBLL.AddOrder(customer);
            List<SepetModel> model = Session["Sepet"] as List<SepetModel>;
            foreach (SepetModel item in model)
            {
                Products product = productBLL.GetProduct(item.ProductID);
                orderdetailBLL.AddOrderDetail(product, item.Quantity, orderID);
            }
            return RedirectToAction("Index");
        }
    }
}

Melidya2.UI/Controllers/ProductController.cs
using Melidya2.BLL;
using Melidya2.Entity;
using Melidya2.UI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Melidya2.UI.Controllers
{
    public class ProductController : Controller
    {
        ProductBLL productBLL = new ProductBLL();

        // GET: Product

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Products()
        {
            List<Products> products = productBLL.GetProducts();
            return View(products);
        }

        public ActionResult Sepet()
        {
            decimal toplamfiyat = 0;
            decimal subtotal = 0;
            List<SepetModel> models = Session["Sepet"] as List<SepetModel>;

            foreach (SepetModel item in models)
            {
                subtotal += Convert.ToDecimal(item.Quantity * item.Price);
            }

            toplamfiyat = subtotal + (decimal)6.90;

            Session["Count"] = models.Count();
            Session["Subtotal"] = subtotal;
            Session["Toplam"] = toplamfiyat;
            return View(models);
        }

        public ActionResult AddSepet(int id)
        {
            Products product = productBLL.GetProduct(id);
            if (Session["Sepet"] == null)
            {
                List<SepetModel> newModel = new List<SepetModel>();
                Session["Sepet"] = newModel;
            }
            SepetModel model = new SepetModel
            {
                ProductName = product.ProductName,
                ProductID = product.ProductID,
                Price = product.UnitPrice,
                Quantity = 1
            };
            List<SepetModel> models = Session["Sepet"] as List<SepetModel>;
            if (models != null)
            {
                SepetModel sepet = models.Find(x => x.ProductID == model.ProductID);
                if (sepet != null)
                {
                    sepet.Quantity += 1;
                }
                else
                {
                    models.Add(model);
                }
            }
            else
            {
                models.Add(model);
            }
            Session["Count"] = models.Count();
            return RedirectToAction("Products");
        }

        public ActionResult DeleteSepet(int id)
        {
            List<SepetModel> models = Session["Sepet"] as List<SepetModel>;
            if (Session["Sepet"] != null)
            {
                SepetModel sepet = models.Find(x => x.ProductID == id);

                if (sepet.Quantity > 1)
                {
                    sepet.Quantity -= 1;
                }
                else
                {
                    models.Remove(sepet);
                }
            }
            return RedirectToAction("Sepet", "Product");

        }
    }
}

Melidya2.UI/Controllers/ProfilController.cs
using Melidya2.BLL;
using Melidya2.Entity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Melidya2.UI.Controllers
{
    public class ProfilController : Controller
    {
        CustomerBLL customerBLL = new CustomerBLL();
        // GET: Profil
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult UserProfile()
        {
            Customers customer = Session["Login"] as Customers;
            return View(customer);
        }

        public ActionResult EditProfile(string id)
        {
            Customers customer = customerBLL.GetCustomer(id);
            return View(customer);
        }

        [HttpPost]
        public ActionResult EditProfile(Customers customer)
        {
            Customers cust = customerBLL.GetCustomer(customer.CustomerID);
            cust.CustomerID = customer.CustomerID;
            cust.CustomerDemographics = customer.CustomerDemographics;
            cust.Country = customer.Country;
            cust.Fax = customer.Fax;
            cust.Password = customer.Password;
            cust.PostalCode = customer.PostalCode;
            cust.Region = customer.Region;
            cust.Phone = customer.Phone;
            cust.ContactName = customer.ContactName;
            cust.ContactTitle = customer.ContactTitle;
            cust.CompanyName = customer.CompanyName;
            cust.Address = customer.Address;
            cust.City = customer.City;

            customerBLL.Update(cust);
            return RedirectToAction("UserProfile");
        }
    }
}

Melidya2.UI/Views/Home/Login.cshtml
@using Melidya2.Entity
@model Customers

@{
    ViewBag.Title = "Login";
}

@using (Html.BeginForm("Login", "Home", FormMethod.Post))
{
    <br />
    <br />
    @Html.TextBoxFor(x => x.CustomerID, new { @class = "form-control", placeholder = "Kullanıcı Adı" })
    @Html.TextBoxFor(x => x.Password, new { @class = "form-control", @type = "password", placeholder = "Şifre" })
    <br />
    <input type="submit" value="Giriş" class="btn btn-danger">
}

Melidya2.UI/Views/Home/LoginHata.cshtml
@using Melidya2.Entity
@model Customers

@using (Html.BeginForm("Login", "Home", FormMethod.Post))
{
<div class="jumbotron">
    <h1 class="display-4">Hata!</h1>
    <hr class="my-4">
    <p>Geçersiz Kullanıcı Adı veya Şifre Lütfen Tekrar Dene.</p>
    <a class="btn btn-primary" href="/Home/Login">Giriş</a>
</div>
    
}

Melidya2.UI/Views/Order/Index.cshtml
@using Melidya2.Entity
@model List<Orders>
@{
    ViewBag.Title = "Index";
}


<table class="table">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">contact name</th>
            <th scope="col">order date</th>
            <th scope="col">işlemler</th>
        </tr>
    </thead>
    <tbody>
        @foreach (Orders item in Model)
        {
            <tr>
                <th scope="row">@item.OrderID</th>
                <td>@item.Customers.ContactName</td>
                <td>@item.OrderDate</td>
                <td><a href="/Order/OrderDetail/@item.OrderID" class="btn btn-success">Detay</a></td>
            </tr>
        }
    </tbody>
</table>

Melidya2.UI/Views/Order/OrderDetail.cshtml
@model IEnumerable<Melidya2.Entity.Order_Details>

@{
    ViewBag.Title = "OrderDetail";
}

<h2>OrderDetail</h2>


<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Products.ProductName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UnitPrice)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Discount)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem=>item.Products.ProductName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.UnitPrice)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Discount)
        </td>
    </tr>
}

</table>

Melidya2.UI/Views/Product/Products.cshtml
@using Melidya2.Entity
@model List<Products>

@{
    ViewBag.Title = "Products";
}
<div class="container">
    <div class="row">
        @foreach (Products item in Model)
        {
            <div class="card col-md-4" style="width: 15rem;">
                <img src="~/Image/narli-parmak-fitil-180-15-B.jpg" class="card-img-top">
                <div class="card-body">
                    <h5 class="card-title">@item.ProductName</h5>
                    <p class="card-text">@item.UnitPrice</p>
                    <a href="/Product/AddSepet/@item.ProductID" class="btn btn-primary">Sepete Ekle</a>
                </div>
            </div>
        }
    </div>
</div>

Melidya2.UI/Views/Product/Sepet.cshtml
@using Melidya2.UI.Models
@model  List<SepetModel>
@{
    ViewBag.Title = "Sepet";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>

<div class="container mb-4">
    <div class="row">
        <div class="col-12">
            <div class="table-responsive">
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th scope="col"> </th>
                            <th scope="col">Ürünler</th>
                            <th scope="col">Stok Durumu</th>
                            <th scope="col" class="text-center">Adet</th>
                            <th scope="col" class="text-right">Adet Fiyat</th>
                            <th> </th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (SepetModel item in Model)
                        {
                            <tr>
                                <td>
                                    <img src="~/Image/narli-parmak-fitil-180-15-B.jpg" width="50" height="50" />
                                </td>
                                <td>@item.ProductName</td>
                                <td>In stock</td>
                                <td>@item.Quantity</td>
                                <td class="text-right">@item.Price TL</td>
                                <td class="text-right"><a href="/Product/DeleteSepet/@item.ProductID" class="btn btn-sm btn-danger"><i class="glyphicon glyphicon-trash"></i> </a> </td>
                            </tr>
                        }

                        <tr>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td>Ara Toplam</td>
                            <td class="text-right">@Session["Subtotal"].ToString() TL</td>
                        </tr>
                        <tr>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td>Kargo</td>
                            <td class="text-right">6,90 TL</td>
                        </tr>
                        <tr>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td><strong>Toplam</strong></td>
                            <td class="text-right"><strong>@Session["Toplam"].ToString() TL</strong></td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
        <div class="col mb-2">
            <div class="row">
                <div class="col-sm-12  col-md-6">
                    <a href="/Product/Products/" class="btn btn-block btn-primary">Alışverişe Devam Et</a>
                </div>
                <div class="col-sm-12 col-md-6 text-right">
                    <a href="/Order/AddOrder" class="btn  btn-block btn-success">Siparişi Tamamla</a>
                </div>
            </div>
        </div>
    </div>
</div>

Melidya2.UI/Views/Profil/EditProfile.cshtml
@model Melidya2.Entity.Customers

@{
    ViewBag.Title = "EditProfile";
}


@using (Html.BeginForm("EditProfile", "Profil", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.CustomerID)

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CompanyName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CompanyName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CompanyName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ContactName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ContactName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ContactName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ContactTitle, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ContactTitle, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ContactTitle, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Region, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Region, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Region, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PostalCode, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PostalCode, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PostalCode, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Country, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Country, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Country, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Fax, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Fax, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Fax, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-success" />
            </div>
        </div>
    </div>
}

Melidya2.UI/Views/Profil/UserProfile.cshtml
@model Melidya2.Entity.Customers

@{
    ViewBag.Title = "UserProfile";
}

<h2>UserProfile</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Password)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Password)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CompanyName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CompanyName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ContactName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ContactName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ContactTitle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ContactTitle)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.City)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.City)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Region)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Region)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PostalCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PostalCode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Country)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Country)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Phone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Phone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Fax)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Fax)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "EditProfile", new { id = Model.CustomerID })
</p>

Melidya2.UI/Views/Shared/_Layout.cshtml
@using Melidya2.Entity
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
    <link rel='stylesheet' href='https://use.fontawesome.com/releases/v5.7.0/css/all.css' integrity='sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ' crossorigin='anonymous'>

</head>
<body>

    @{
        Customers customer = null;
        if (Session["Login"] != null)
        {
            customer = Session["Login"] as Customers;
        }
    }

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
        <a class="navbar-brand" href="#"> Melidya</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="/Order/Index"><i class="fas fa-home"></i>Anasayfa <span class="sr-only">(current)</span></a>
                </li>
            </ul>

            <ul class="navbar-nav ml-auto">
                @if (Session["Login"] != null)
                {
                    <li class="nav-item active">
                        <a class="nav-link" href="/Product/Products">Ürünler <span class="sr-only">(current)</span>
                        </a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link " href="/Profil/UserProfile"><i class="glyphicon glyphicon-user">@customer.ContactName </i><span class="sr-only">(current)</span>
                        </a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link" href="/Product/Sepet">
                            <i class='fas fa-cart-arrow-down'>Sepetim</i>
                            
                            @if (Session["Sepet"] != null)
                            {
                                @Session["Count"]
                            }
                            
                        </a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link" href="/Home/Logout">Çıkış <span class="sr-only">(current)</span></a>
                    </li>


                }
                else
                {
                    <li class="nav-item active">
                        <a class="nav-link" href="/Home/Login">Giriş <span class="sr-only">(current)</span></a>
                    </li>

                }
            </ul>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-3.0.0.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>